### ISSUE TITLE
Error with contributing

### ISSUE THREAD

**Issue by Kingpin2557** [dostonnabotov/sass-template#2]
Hey, I am trying to contribute a mixin but I am having trouble doing so. this would be my first time every contributing to an online project. my issue is that I had first made my changes on the main branch, then I thought it be better to create a branch specifically for this mixin to then make a pull request. However, it keeps saying access is denied

**Comment by Kingpin2557** [comment]
I also hope my snipped is correct for the scss.json
`  {
    "title": "flex-box mixin",
    "description": "This mixin creates a flex-box, properties order goes as followed flex, direction, justify-content, align-items and finally gap. If you want to ignore one of them you can use the keyword 'null' as a value",
    "code": [
     "@mixin flex-box(",
     "$display: flex",
      "$direction: null",
      "$justify: null",
      "$align: null",
      "$gap: null) {",
      "display: $display;",
      "flex-direction: $direction;",
      "justify-content: $justify;",
      "align-items: $align;",
      "gap: $gap;",
      "}"
    ],
    "tags": ["scss", "layout", "SASS", "mixin"],
    "author": "LodeSnaet"
  }`

**Comment by technoph1le** [comment]
Hi. Congrats on first contribution. I will review it and let you know the problem

**Comment by technoph1le** [comment]
@LodeSnaet I didn't notice that you were in "Sass Template" repo. The repo you're trying to contribute is here 🙂:
- https://github.com/dostonnabotov/quicksnip

**Comment by Kingpin2557** [comment]
I am not sure how you can review my code since I am unable to make the pull request to that repo.

**Comment by technoph1le** [comment]
@LodeSnaet First you will need to fork (copy) the [repo](https://github.com/dostonnabotov/quicksnip) in your own github repo.

And, once you've made the changes, head over to [pull requests page](https://github.com/dostonnabotov/quicksnip/pulls), and create a new pull request. 

Let me know if you face any issues. If none of these worked, create a new issue [here](https://github.com/dostonnabotov/quicksnip/issues), and people will help you out.
